import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Root } from "@/components/Root/Root";
import { I18nProvider } from "@/core/i18n/provider";
import { getLocale } from "next-intl/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body>
        <I18nProvider>
          <Root>
            {children}
          </Root>
        </I18nProvider>
      </body>
    </html>
  );
}
